version: "3"

services:
  registry:
    image: registry:2.8
    container_name: registry-srv
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /var/data/registry:/var/lib/registry
      - ./registry/.htpasswd:/root/.htpasswd
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH_HTPASSWD_REALM: basic-realm
      REGISTRY_AUTH_HTPASSWD_PATH: /root/.htpasswd
